### PR TITLE
Add list of available skins to README

### PR DESCRIPTION
**Pull request by michaelsavchuk**

### CODE REVIEW

**Comment by itaditya** [comment]
Please add the instruction also. Like how you can use each skin.

**Comment by michaelsavchuk** [comment]
But you already have instructions for that in other sections of the README...

**Comment by itaditya** [comment]
Yeah you are correct but as you can notice there are fragmented across the README, also many developers would be confused about how to add their custom skin to the project. They may skip over the line where it says that the classname is same as the skin name and the css file name should also be the same. 

To avoid the confusion, it would be better if they get a list of examples for each skin.

**Review by itaditya — CHANGES_REQUESTED** [review]
Please make the changes given in the comments

**Comment by michaelsavchuk** [comment]
Added in second commit.

**Review by itaditya — CHANGES_REQUESTED** [review]
New skins have been added, but you haven't included them. Ensure that all the latest ones are added.

**Comment by michaelsavchuk** [comment]
I didn't add it because it was not in the [`dist`](https://github.com/itaditya/circlebars/tree/master/dist) folder, which led me to believe that it wasn't ready for release yet. I added the Matte Black skin in the third commit, but I recommend updating the dist folder and the link in the README accordingly.

**Pull request merged**
